kind: Pod
apiVersion: v1
metadata:
   name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-test
  containers:
    - name: pv-container
      image: bitnami/nginx
      securityContext: 
        privileged: yes
      volumeMounts:
        - mountPath: "/app"
          name: pv-storage