kind: Pod
apiVersion: v1
metadata:
   name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: pv-claim-1
  containers:
    - name: pv-container
      image: bitnami/nginx
      securityContext:  
        privileged: true
      volumeMounts:
        - mountPath: "/app"
          name: pv-storage