kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-volume-nginx
  labels:
      type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mynginx-data"