apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity
spec:
  affinity:
    nodeAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution: 
        nodeSelectorTerms:
        - matchExpressions:
          - key: env
            operator: In 
            values:
            - dev
  containers:
  - name: with-node-affinity
    image: bitnami/nginx